spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://123.57.157.135:3306/student_score?serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
#常规配置
    initialSize: 5
    minIdle: 5


#    配置监控统计拦截的filters，去掉后监控界面的SQL无法统计，walls用于防火墙
    filters:
      commons-log.connection-logger-name: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    #  配置redis
    #默认redis数据库为db0
  redis:
    database: 0
    host: 123.57.157.135
    port: 6379
  mail:
    host: smtp.qq.com
    username: 997150986@qq.com
    password: rwebjgxzaxxlbdcg
    default-encoding: UTF-8
    port: 465
    auth: true
    properties:
      mail:
        smtp:
          ssl:
            enable: true
      imap:
        ssl:
          socketFactory:
            fallback: false
server:
  port: 8080
  servlet:
    context-path: /student_score

mybatis:
  mapper-locations: classpath:/mappers/*Mapper.xml
  type-aliases-package: com.student_score.dao
  configuration:
    map-underscore-to-camel-case: true

